name: cloudspecialists
favicon: null
layout_spectrum: 0.43522068951278925
typography_spectrum: 0.77956
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#41b6e5'
    - '#fbfbfb'
    - '#040a42'
    - '#485169'
    - '#b36545'
  brandStrength: 0.75
  lightness: 0.8864309985656291
  saturation: 0.3893551838118583
  rhythmicContrast: 0.10288897412829101
purpose: []
